# 0: no debugging
# 1: light debugging
# 2: heavy debugging
DEBUG_LEVEL = 0

# CONSTANTS IN NEURAL NET TRAINER
NUM_EPOCHS = 1
LEARNING_RATE = 0.001
BATCH_SIZE = 4


# CONSTANTS IN MCTS
MCTS_EPSILON = 0.2
GAME_MOVE_EPSILON = 0.2
SQRT_2 = 1.41
ROLLOUTS = 1000